/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Random;
import javax.swing.ButtonModel;
import models.parametres.*;
import models.votes.*;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.PieSectionLabelGenerator;
import org.jfree.chart.labels.StandardPieSectionLabelGenerator;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.general.DefaultPieDataset;
/**
 *
 * @author Camelia
 */
public class Parametres extends javax.swing.JFrame {

    /**
     * Creates new form choisirNElecteurs
     */
    public Parametres() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrutins = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        axe1Parametrage = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        axe2Parametrage = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        c3NomPrenom = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nbElecteurs = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        c1Axe2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        c1NomPrenom = new javax.swing.JTextField();
        c1Axe1 = new javax.swing.JTextField();
        c2Axe2 = new javax.swing.JTextField();
        c2Axe1 = new javax.swing.JTextField();
        c3Axe1 = new javax.swing.JTextField();
        c2NomPrenom = new javax.swing.JTextField();
        c3Axe2 = new javax.swing.JTextField();
        c4Axe1 = new javax.swing.JTextField();
        c4NomPrenom = new javax.swing.JTextField();
        c5Axe2 = new javax.swing.JTextField();
        c5NomPrenom = new javax.swing.JTextField();
        c5Axe1 = new javax.swing.JTextField();
        c4Axe2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        deuxTours = new javax.swing.JRadioButton();
        unTour = new javax.swing.JRadioButton();
        alternatif = new javax.swing.JRadioButton();
        approbation = new javax.swing.JRadioButton();
        borda = new javax.swing.JRadioButton();
        valider = new javax.swing.JButton();
        erreur = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Paramétrage des axes");

        axe1Parametrage.setText("Axe 1");

        jLabel2.setText("Axe n°1 : ");

        jLabel3.setText("Axe n°2 : ");

        axe2Parametrage.setText("Axe 2");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Paramétrage des electeurs");

        jLabel5.setText("Veuillez saisir le nombre d'électeurs : ");

        c3NomPrenom.setText("Candidat 3");
        c3NomPrenom.setToolTipText("Saisir le nom et le prénom");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Paramétrage des candidats");

        jLabel7.setText("Candidat 4 : ");

        nbElecteurs.setText("100");

        jLabel8.setText("Candidat 1 : ");

        c1Axe2.setText("0.2");
        c1Axe2.setToolTipText("");

        jLabel9.setText("Candidat 2 : ");

        jLabel10.setText("Candidat 5 : ");

        jLabel11.setText("Candidat 3 : ");

        c1NomPrenom.setText("Candidat 1");
        c1NomPrenom.setToolTipText("Saisir le nom et le prénom");

        c1Axe1.setText("0.1");

        c2Axe2.setText("0.4");

        c2Axe1.setText("0.3");

        c3Axe1.setText("0.5");

        c2NomPrenom.setText("Candidat 2");
        c2NomPrenom.setToolTipText("Saisir le nom et le prénom");

        c3Axe2.setText("0.6");

        c4Axe1.setText("0.7");

        c4NomPrenom.setText("Candidat 4");
        c4NomPrenom.setToolTipText("Saisir le nom et le prénom");

        c5Axe2.setText("1");

        c5NomPrenom.setText("Candidat 5 ");
        c5NomPrenom.setToolTipText("Saisir le nom et le prénom");

        c5Axe1.setText("0.9");

        c4Axe2.setText("0.8");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Mode de scrutin");

        scrutins.add(deuxTours);
        deuxTours.setText("Deux tours");

        scrutins.add(unTour);
        unTour.setSelected(true);
        unTour.setText("Un Tour");

        scrutins.add(alternatif);
        alternatif.setText("Alternatif");

        scrutins.add(approbation);
        approbation.setText("Approbation");

        scrutins.add(borda);
        borda.setText("Borda");

        valider.setText("Valider");
        valider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                validerMouseClicked(evt);
            }
        });

        erreur.setBackground(new java.awt.Color(204, 0, 0));

        jLabel13.setText("Axe 2 :");

        jLabel14.setText("Axe 2 :");

        jLabel15.setText("Axe 2 :");

        jLabel16.setText("Axe 2 :");

        jLabel17.setText("Axe 2 :");

        jLabel18.setText("Axe 1 :");

        jLabel19.setText("Axe 1 :");

        jLabel20.setText("Axe 1 :");

        jLabel21.setText("Axe 1 :");

        jLabel22.setText("Axe 1 :");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel23.setText("En cas de saisie incorrecte de valeurs, elles seront générées au hasard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c5NomPrenom)
                            .addComponent(c4NomPrenom)
                            .addComponent(c3NomPrenom)
                            .addComponent(c2NomPrenom)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(c1NomPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(35, 35, 35)
                        .addComponent(axe1Parametrage, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(axe2Parametrage, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(186, 186, 186))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(c4Axe1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(c5Axe1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(c3Axe1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(c2Axe1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(c1Axe1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(c2Axe2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(c1Axe2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(c3Axe2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(c4Axe2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(c5Axe2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42))))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nbElecteurs, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(unTour)
                                .addGap(43, 43, 43)
                                .addComponent(deuxTours))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addComponent(alternatif)
                        .addGap(43, 43, 43)
                        .addComponent(approbation)
                        .addGap(47, 47, 47)
                        .addComponent(borda)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(erreur, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(valider, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(1, 1, 1)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(axe1Parametrage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(axe2Parametrage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nbElecteurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(c1Axe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c1NomPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c1Axe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel18))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c2Axe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c2NomPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c2Axe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(c3NomPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c3Axe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c3Axe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c4NomPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c4Axe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c4Axe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel22)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c5Axe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c5Axe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(c5NomPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel17)
                        .addComponent(jLabel19)))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unTour)
                    .addComponent(deuxTours)
                    .addComponent(alternatif)
                    .addComponent(approbation)
                    .addComponent(borda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valider)
                    .addComponent(erreur))
                .addGap(25, 25, 25))
        );

        jLabel13.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private double getValAxe(String axeString)
    {
        double axe;
        Random rand = new Random();
        try
        {
            axe = Double.parseDouble(axeString);
        }
        catch(Exception e)
        {
            axe = rand.nextDouble();
        }
        return axe;
        
    }
    
    private void validerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validerMouseClicked
        //Axes
        String axe1 = axe1Parametrage.getText();
        String axe2 = axe2Parametrage.getText();
        Axe axePremier = new Axe(axe1);
        Axe axeDeuxieme = new Axe(axe2);
        Axe[] axes = {axePremier, axeDeuxieme};
        //Electeurs
        int nbElecteur;
        try
        {
            nbElecteur = Integer.parseInt(nbElecteurs.getText());
        }
        catch(Exception e)
        {
            nbElecteur = 100;
        }
        
        Electeur[] electeurs = new Electeur[nbElecteur];
        Random rand;
        double val1;
        double val2;
        
        for(int i=0;i<nbElecteur;i++)
        {
            rand = new Random();
            val1 = rand.nextDouble();
            val2 = rand.nextDouble();
            double[] valAxes = {val1,val2};
            Electeur electeur = new Electeur(axes,valAxes);
            electeurs[i] = electeur;
        }
        //Candidats
        Candidat[] candidats = new Candidat[5];
        //Candidat 1
        double c1_axe1 = getValAxe(c1Axe1.getText());
        double c1_axe2 = getValAxe(c1Axe2.getText());
        double[] valAxes = {c1_axe1,c1_axe2};
        candidats[0] = new Candidat(axes,valAxes,c1NomPrenom.getText());
        //Candidat 2
        double c2_axe1 = getValAxe(c2Axe1.getText());
        double c2_axe2 = getValAxe(c2Axe2.getText());
        double[] valAxes2 = {c2_axe1,c2_axe2};
        candidats[1] = new Candidat(axes,valAxes2,c2NomPrenom.getText());
        //Candidat 3
        String nomPrenom3 = c3NomPrenom.getText();
        double c3_axe1 = getValAxe(c3Axe1.getText());
        double c3_axe2 = getValAxe(c3Axe2.getText());
        double[] valAxes3 = {c3_axe1,c3_axe2};
        candidats[2] = new Candidat(axes,valAxes3,c3NomPrenom.getText());
        //Candidat 4
        String nomPrenom4 = c4NomPrenom.getText();
        double c4_axe1 = getValAxe(c4Axe1.getText());
        double c4_axe2 = getValAxe(c4Axe2.getText());
        double[] valAxes4 = {c4_axe1,c4_axe2};
        candidats[3] = new Candidat(axes,valAxes4,c4NomPrenom.getText());
        //Candidat 5
        String nomPrenom5 = c5NomPrenom.getText();
        double c5_axe1 = getValAxe(c5Axe1.getText());
        double c5_axe2 = getValAxe(c5Axe2.getText());
        double[] valAxes5 = {c5_axe1,c5_axe2};
        candidats[4] = new Candidat(axes,valAxes5,c5NomPrenom.getText());
        
        //Scrutin
        ButtonModel scrutinButton = scrutins.getSelection();
        Scrutin scrutin;
        if(scrutinButton == unTour.getModel())
        {
            scrutin = new UnTour(candidats, electeurs);
        }
        else if(scrutinButton == deuxTours.getModel())
        {
            scrutin = new DeuxTours(candidats, electeurs);
        }
        else if(scrutinButton == approbation.getModel())
        {
            HashMap<Electeur,Integer> nbVotes = new HashMap<>(); 
            for(int i=0;i<electeurs.length;i++)
            {
                nbVotes.put(electeurs[i],2);
            }
            scrutin = new Approbation(candidats, nbVotes);
        }
        else if(scrutinButton == alternatif.getModel())
        {
            scrutin = new Alternatif(candidats, electeurs);
        }
        else
        {
             scrutin = new Borda(candidats, electeurs);
        }
        appelCamembert(scrutin);
    }//GEN-LAST:event_validerMouseClicked
    
    private void appelCamembert(Scrutin scrutin)
    {
        //Simuler une election
        LinkedHashMap<Candidat,Double> resultatScrutin;
        scrutin.simulation(scrutin.getCandidats());
        resultatScrutin = scrutin.getResultatScrutin();
        
        DefaultPieDataset camembert = new DefaultPieDataset();
        List<Candidat> candidatsListe = new ArrayList<Candidat>(resultatScrutin.keySet());
	List<Double> pourcentsListe = new ArrayList<Double>(resultatScrutin.values());
        
        for(int i=0;i<candidatsListe.size();i++)
        {
            camembert.setValue(candidatsListe.get(i).getNomPrenom(), pourcentsListe.get(i));
        }
        
        JFreeChart chart = ChartFactory.createPieChart("Resultat pour le type de simulation suivant : "+scrutin.getTypeScrutin(), camembert, true, true, false);
        PiePlot p=(PiePlot)chart.getPlot();
        PieSectionLabelGenerator labelGenerator = new StandardPieSectionLabelGenerator("{0} = {2}");
        p.setLabelGenerator(labelGenerator);
        //p.setForegroundAlpha(TOP_ALIGNMENT);
        ChartFrame frame = new ChartFrame("Resultat pour le type de simulation suivant : "+scrutin.getTypeScrutin(),chart);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int height = screenSize.height;
        int width = screenSize.width;
        frame.setSize(width/2, height/2);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        
        
        
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parametres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parametres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parametres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parametres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Parametres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton alternatif;
    private javax.swing.JRadioButton approbation;
    private javax.swing.JTextField axe1Parametrage;
    private javax.swing.JTextField axe2Parametrage;
    private javax.swing.JRadioButton borda;
    private javax.swing.JTextField c1Axe1;
    private javax.swing.JTextField c1Axe2;
    private javax.swing.JTextField c1NomPrenom;
    private javax.swing.JTextField c2Axe1;
    private javax.swing.JTextField c2Axe2;
    private javax.swing.JTextField c2NomPrenom;
    private javax.swing.JTextField c3Axe1;
    private javax.swing.JTextField c3Axe2;
    private javax.swing.JTextField c3NomPrenom;
    private javax.swing.JTextField c4Axe1;
    private javax.swing.JTextField c4Axe2;
    private javax.swing.JTextField c4NomPrenom;
    private javax.swing.JTextField c5Axe1;
    private javax.swing.JTextField c5Axe2;
    private javax.swing.JTextField c5NomPrenom;
    private javax.swing.JRadioButton deuxTours;
    private javax.swing.JLabel erreur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nbElecteurs;
    private javax.swing.ButtonGroup scrutins;
    private javax.swing.JRadioButton unTour;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables
}
